server:
  port: 8090
  servlet:
    context-path: /api

spring:
  application:
    name: myblog

  datasource:
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?ssl-mode=REQUIRED
    #url: jdbc:mariadb://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE_NAME}?ssl-mode=REQUIRED
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # ddl-auto values:
      # create-drop -> creazione del db all'all'avvio dell'applicazione e distruzione del db alla chiusura dell'appliocazione
      # update -> aggiorna il db con le tabelle 'nuove', modifica quelle attuali, non elimina eventuali colonne che non esistono piÃ¹
      # validated -> confronta le entitÃ  con le tabelle e solleva eccezioni se ci sono incongruenze
      # none: non viene fatto nulla (da usare assolutamente in produzione)
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      #dialect: org.hibernate.dialect.MariaDBDialect
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
    show-sql: true
    open-in-view: false


spring-doc:
  swagger-ui:
    enabled: true
    # hostname:port/swagger-ui.html => localhost:8090/api/swagger-ui.html
    path: /swagger-ui.html

logging:
  level:
    it.cgmconsulting.myblog: info
    org.hibernate.orm.jdbc.bind: trace
    org.springframework: info

# CUSTOM PROPERTIES
application:
  security:
    jwt:
      tokenType: Bearer
      secret-key: WS27AFx7dmB8OEueK6RW5F5C51MwDH57CoI6NDgZCBJ2306qBZISUL3KYaF9RM67
      expiration: 86400000 #milliseconds -> 1 day